### ISSUE TITLE
Ability to configure concurrency for image factory

### ISSUE THREAD

**Issue by sukrit007** [totem/docker-image-factory#20]
As a totem developer, I need to restrict concurrency for docker builds that executes concurrently by image factory in order to prevent crashes when multiple github hooks fire at once.

**Comment by kylehuntsman** [comment]
PR [#22](https://github.com/totem/docker-image-factory/pull/22) - Feature Job Queues

Adds a configurable amount of concurrent jobs using a FIFO queue. Concurrent configuration can be changed in the config files. Defaults to one if no configuration is specified.
